### ISSUE TITLE
Error trying to download Forge

### ISSUE THREAD

**Issue by mapletlan** [cdbbnnyCode/modpack-installer#34] opened 2023-09-16 23:36 UTC
Hi, I'm getting a "-1" error trying to download Forge when I try to run python install.py on my modpack zip. I get a url to download the right version of forge in the terminal, when I open it in the browser the forge installer jar downloads. I've tried running installer.py with --manual and --open-browser, both gave "-1 error trying to download Forge". 

Thanks for the great program!

**Comment by cdbbnnyCode** [comment] 2023-09-17 01:42
Looks like it's running into a Requests-related error (probably network problems or the Forge website is blocking non-browser connections now), but my *excellent* error handling code doesn't tell what the error actually is.

I'll do some testing to see if I can reproduce the error.

As a quick test, can you change line 47 in `util.py` to
```python
except requests.RequestException as e:
```
and add
```python
print(repr(e))
```
after it? Then it should print out why it's failing.

**Comment by jayx11** [comment] 2023-09-19 21:52
im not OP, but i had the same error, heres my output:
```[pack data already unzipped]
[minecraft dir already created]
Installing modloader
Updating user launcher profiles
Downloading "https://maven.minecraftforge.net/net/minecraftforge/forge/1.18.2-40.2.0/forge-1.18.2-40.2.0-installer.jar
InvalidSchema('No connection adapters were found for \'"https://maven.minecraftforge.net/net/minecraftforge/forge/1.18.2-40.2.0/forge-1.18.2-40.2.0-installer.jar\'')

Traceback (most recent call last):
  File "install.py", line 393, in <module>
    main(
  File "install.py", line 243, in main
    modloaders[modloader].main(manifest, mcver, mlver, packname, user_mcdir, manual)
  File "/home/gabe/Desktop/modpack-installer-master/forge_install.py", line 44, in main
    resp = download(url, outpath, True)
  File "/home/gabe/Desktop/modpack-installer-master/util.py", line 55, in download
    return r.status_code
UnboundLocalError: local variable 'r' referenced before assignment```

**Comment by cdbbnnyCode** [comment] 2023-09-20 00:35
Oh that's really subtle... looks like something is putting a double quote at the beginning of the URL. Thanks @jayx11

**Comment by cdbbnnyCode** [comment] 2023-09-20 01:48
Should be fixed in ed95eb3. Please confirm that this fixes the issue.

**Comment by mapletlan** [comment] 2023-09-22 19:11
@cdbbnnyCode Sorry about formatting, git newb here. 

I changed the lines in util.py and received the same error as jayx11: 

> $ python install.py gcp-client-1.7.1.zip 
> [pack data already unzipped]
> [minecraft dir already created]
> Installing modloader
> Updating user launcher profiles
> Downloading "https://maven.minecraftforge.net/net/minecraftforge/forge/1.12.2-14.23.5.2860/forge-1.12.2-14.23.5.2860-installer.jar
> InvalidSchema('No connection adapters were found for \'"https://maven.minecraftforge.net/net/minecraftforge/forge/1.12.2-14.23.5.2860/forge-1.12.2-14.23.5.2860-installer.jar\'')
> 
> Traceback (most recent call last):
>   File "*/Downloads/modpack-installer-2.3.4/install.py", line 393, in <module>
>     main(
>   File "*/Downloads/modpack-installer-2.3.4/install.py", line 243, in main
>     modloaders[modloader].main(manifest, mcver, mlver, packname, user_mcdir, manual)
>   File "*/Downloads/modpack-installer-2.3.4/forge_install.py", line 44, in main
>     resp = download(url, outpath, True)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "*/Downloads/modpack-installer-2.3.4/util.py", line 55, in download
>     return r.status_code
>            ^
> UnboundLocalError: cannot access local variable 'r' where it is not associated with a value

I also tried replacing util.py and forge_install.py you committed 3 days ago and received a long output tracing from: 

> ... install.py", line 20, in <module>, import forge_install
> ... forge_install.py", line 1, in <module>
> {"payload":{"allShortcutsEnabled":false,"fileTree":{"":{"items":[{"name":".gitignore","path":".gitignore","contentType":"file"},{"name":"ForgeHack.java","path":"ForgeHack.java","contentType":"file"},{"name":"LICENSE","path":"LICENSE","contentType":"file"},{"name":"README.md","path":"README.md","contentType":"file"},{"name":"clean.py","path":"clean.py","contentType":"file"},{"name":"fabric_install.py","path":"fabric_install.py","contentType":"file"},{"name":"forge_install.py","path":"forge_install.py","contentType":"file"},{"name":"install.py","path":"install.py","contentType":"file"},{"name":"migrate.py","path":"migrate.py","contentType":"file"},{"name":"mod_download.py","path":"mod_download.py","contentType":"file"},{"name":"util.py","path":"util.py","contentType":"file"}],"totalCount":11}},"fileTreeProcessingTime":3.0747999999999998,"foldersToFetch":[],"reducedMotionEnabled":null,"repo":{"id":258856885,"defaultBranch":"master","name":"modpack-installer","ownerLogin":"cdbbnnyCode","currentUserCanPush":false,"isFork":false,"isEmpty":false,"createdAt":"2020-04-25T19:28:09.000Z","ownerAvatar":"https://avatars.githubusercontent.com/u/18408621?v=4","public":true,"private":false,"isOrgOwned":false},"symbolsExpanded":false,"treeExpanded":true,"refInfo":{"name":"master","listCacheKey":"v0:1684763399.537899","canEdit":false,"refType":"branch","currentOid":"ed95eb38db0f1bb194d0d239b76d94f6fd2b21ea"},"path":"forge_install.py","currentUser":null,"blob":{"rawLines":["#!/usr/bin/env python3","import os","import re","import subprocess","import sys","import time","from util import *","","# https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2847/forge-1.12.2-14.23.5.2847-universal.jar","","def get_forge_url(mcver, mlver):","    index_url = 'https://files.minecraftforge.net/net/minecraftforge/forge/index_%s.html' \\","            % mcver","","    outpath = '/tmp/forge-%s-index.html' % mcver","    if not os.path.exists(outpath):","        resp = download(index_url, outpath, False)","        if resp != 200:","            print(\"Got %d error trying to download Forge download index\" % resp)","            return \"\"","","    with open(outpath, 'r') as f:","        match = re.search(\"href=\\\"(.*%s.*\\.jar)\\\"\" % mlver, f.read())","        if match:","            url = match.group(1)","        else:","            print(\"Could not find Forge download URL for version %s (Minecraft version %s)\" % (mlver, mcver))","            return \"\"","","    return url","","def guess_forge_url(mcver, mlver):","    forge_fullver = mcver + '-' + mlver","    return 'https://files.minecraftforge.net/maven/net/minecraftforge/forge/%s/forge-%s-installer.jar' % (forge_fullver, forge_fullver)","","def main(manifest, mcver, mlver, packname, mc_dir, manual):","    url_providers = [guess_forge_url, get_forge_url]","","    outpath = '/tmp/forge-%s-installer.jar' % (mcver + '-' + mlver)","","    for provider in url_providers:","        if os.path.exists(outpath):","            break","        url = provider(mcver, mlver)","","        resp = download(url, outpath, True)","        if resp != 200:","            print(\"Got %d error trying to download Forge\" % resp)","    else:","        print(\"Failed to download the Forge installer.\")","        sys.exit(2)","","    # Run the Forge auto-install hack","    if manual:","        print(\"Using the manual installer!\")","        print(\"***** NEW: INSTALL TO THE MAIN .MINECRAFT DIRECTORY *****\")","        print(\"*****   (Just hit 'OK' with the default settings)   *****\")","        for i in range(20):","            print(\"^ \", end=\"\", flush=True)","            time.sleep(0.05)","","        subprocess.run(['java', '-jar', outpath])","    else:","        compile_hack = False","        if not os.path.exists('ForgeHack.class'):","

It goes on but didn't seem important, it ends with the output line: 

> NameError: name 'false' is not defined. Did you mean: 'False'?

I'm just manually downloading the scripts so I'm not sure if something went wrong on my end, again git newb here, thanks!

**Comment by cdbbnnyCode** [comment] 2023-09-22 19:19
Do you have the repository cloned with `git`? If so, you should be able to do a `git pull` to update to the latest commit:
```
git reset --hard HEAD
git pull
```

**Comment by cdbbnnyCode** [comment] 2023-09-22 19:22
Actually, it looks like you downloaded from github directly; can you clone the repository from the command line?
```
git clone https://github.com/cdbbnnyCode/modpack-installer
```

**Comment by cdbbnnyCode** [comment] 2023-09-22 20:15
Or you can just download the latest version with the "Code" button on the GitHub page.

**Comment by cdbbnnyCode** [comment] 2023-09-27 15:20
Closing since the original issue is presumably solved.

**Closed as completed by cdbbnnyCode** 2023-09-27 15:20 UTC
